### ISSUE TITLE
deploy: Add --port option to deploy when using --expose

### ISSUE THREAD

**Issue by DonSchenck** [tmds/dotnet-shift#66]
Currently, port 8080 is used. My app uses port 5000. Adding this --port option solves this issue.

**Comment by tmds** [comment]
Is your app an ASP.NET app?

If it is, it should pick up the `ASPNETCORE_URLS` envvar which causes it to use port `8080`.

**Comment by tmds** [comment]
In general, I want to minimize the options on the `deploy` command.

Port `5000` or port `8080`, this should be configurable on the app.

The envvar is set for ASP.NET to pick up port `8080`.

If the app needs another envvar to control the port, it can be set using [ContainerEnvironmentVariable](https://github.com/dotnet/sdk-container-builds/blob/main/docs/ContainerCustomization.md#containerenvironmentvariable).

If there is a need to for apps to use another port than `8080`, we can make it configurable in the project file using [ContainerPort](https://github.com/dotnet/sdk-container-builds/blob/main/docs/ContainerCustomization.md#containerport).

**Comment by tmds** [comment]
> If there is a need to for apps to use another port than 8080, we can make it configurable in the project file using [ContainerPort](https://github.com/dotnet/sdk-container-builds/blob/main/docs/ContainerCustomization.md#containerport).

I've written up a spec for `ContainerPort`: https://github.com/tmds/dotnet-shift/issues/71.

@DonSchenck I don't plan to include `ContainerPort` in the upcoming release, unless you think it is desired to have it already.
